services:
  - type: web
    name: mbse-mbple-workbench
    runtime: static
    branch: main
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    autoDeployTrigger: commit
    envVars:
      - key: NODE_VERSION
        value: "24"
